[general]
email = "alexadane23@gmail.com"

[openai]
api_key = "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"
